config/routes.rb
Photo::Application.routes.draw do
  get "home/index"

  resources :user_sessions, :only => [:new, :create, :destroy]
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :admin, :only => [:index]
  resources :albums
  resources :gallery, :only => [:index]
  match "/gallery_reset" => "gallery#reset"
  resources :pictures, :except => [:index]
  resources :posts, :only => [:new, :create, :index, :destroy]
  resources :volumes, :only => [:new, :create, :index, :destroy] # is this needed?

  match "/about" => "home#about"
  match "/blog" => "home#blog"
  match "/framing" => "home#framing"
  match "/pricing" => "home#pricing"

  match "/set_gallery_session" => "application#set_gallery_session", via: :post
  match "/get_gallery_session" => "application#get_gallery_session", via: :get

  root :to => 'home#index'

end

app/views/admin/index.html.haml
.center.light-grey
  %script{:src => 'galleria.classic.js'}
  %h1{style: "text-decoration:underline;"} Control Panel
  %br

  %h2
    Albums:
  %h4
    = link_to "View/edit all albums", albums_path
  %br
  %h4
    = link_to "Add a new album", new_album_path

  %br
  %h2
    Pictures:
  %h4
    = link_to "Add a new picture", new_picture_path

  %br
  %h2
    Blog:
  %h4
    = link_to "Add a new blog volume", new_volume_path
  %br
  %h4
    = link_to "Add a new blog post", new_post_path

  %br
  %br
  %br
  %br
  = link_to "Logout", :logout, :method => :post

app/views/admin/order.html.haml
.container-group
  .well.sidebar-nav
    %ul.nav.nav-list
      %li.nav-title
        %h4
          Albums
      -@albums.each do |album|
        %li.nav-header{:class => ("active" if params[:album] == album.name)}
          =link_to "#{album.name}", admin_order_url(:album => album.name)

  .container
    .content.gallery
      %h1.center
        = @album.nil? ? "Re-order" : @album.name
      - if @album.nil?
        %h4.center
          Choose an album to re-order pictures
      =#TODO  display @pictures collection as thumbnails
      - if @album
        %table
          - @pictures.in_groups_of(2) do |picture_group|
            %tr.photo-row
              - picture_group.each do |picture|
                %td.photo
                  - if picture
                    -#TODO: change to use cl_image_tag, or remove page
                    = image_tag picture.filename
            %tr.ordering
              - picture_group.each do |picture|
                %td
                  - if picture
                    = select_tag(:order, options_for_select([picture.ordering]))

app/views/admin/upload.html.haml
= simple_form_for :picture, :url => {:action => :create} do |f|
  = f.input :photo_file, :as => 'file'
  = f.input :title
  = f.input :description
  = #f.input :slideshow, :as => check_box, input_html: {checked: false}

  .btn.btn-primary
    = f.submit 'Add picture'