config/routes.rb
Photo::Application.routes.draw do
  get "home/index"

  resources :user_sessions, :only => [:new, :create, :destroy]
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :admin, :only => [:index]
  resources :albums
  resources :gallery, :only => [:index]
  match "/gallery_reset" => "gallery#reset"
  resources :pictures, :except => [:index]
  resources :posts, :only => [:new, :create, :index, :destroy]
  resources :volumes, :only => [:new, :create, :index, :destroy] # is this needed?

  match "/about" => "home#about"
  match "/blog" => "home#blog"
  match "/framing" => "home#framing"
  match "/pricing" => "home#pricing"

  match "/set_gallery_session" => "application#set_gallery_session", via: :post
  match "/get_gallery_session" => "application#get_gallery_session", via: :get

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login

  def blog
    @posts = Post.all.sort_by(&:created_at).reverse! # TODO: kill?
    @volumes = Volume.all.select(&:has_posts?).sort_by(&:created_at)
    volume_id = params[:volume].to_i
    if volume_id > 0
      @current_volume = Volume.find_by_id(volume_id)
    else
      @current_volume = @volumes.try(:last)
    end
  end

  def framing
    @pictures = Picture.all.select{|pic| pic.album.name.capitalize == "Frames"}
  end

  def index
    @pictures = Picture.where("slideshow = ?", true).sort_by{|p| p.album.ordering}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/blog/_sidebar.html.haml
%ul.nav.nav-list#filters{style: "margin-left:auto;margin-right:auto;"}
  %li.nav-header
    %h5{:style => 'font-weight:normal;text-shadow:none;'}
      VOLUMES
  - @volumes.reverse.each do |volume|
    - if volume.id == @current_volume.id
      %li.volume-list-item.active
        = link_to(volume.name.titleize, blog_path(:volume => volume.id), :onClick => "window.location.href=\"#{blog_url(:volume => volume.id)}\";")
    - else
      %li.volume-list-item
        = link_to(volume.name.titleize, blog_path(:volume => volume.id), :onClick => "window.location.href=\"#{blog_url(:volume => volume.id)}\";")