config/routes.rb
Photo::Application.routes.draw do
  get "home/index"

  resources :user_sessions, :only => [:new, :create, :destroy]
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :admin, :only => [:index]
  resources :albums
  resources :gallery, :only => [:index]
  match "/gallery_reset" => "gallery#reset"
  resources :pictures, :except => [:index]
  resources :posts, :only => [:new, :create, :index, :destroy]
  resources :volumes, :only => [:new, :create, :index, :destroy] # is this needed?

  match "/about" => "home#about"
  match "/blog" => "home#blog"
  match "/framing" => "home#framing"
  match "/pricing" => "home#pricing"

  match "/set_gallery_session" => "application#set_gallery_session", via: :post
  match "/get_gallery_session" => "application#get_gallery_session", via: :get

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login

  def blog
    @posts = Post.all.sort_by(&:created_at).reverse! # TODO: kill?
    @volumes = Volume.all.select(&:has_posts?).sort_by(&:created_at)
    volume_id = params[:volume].to_i
    if volume_id > 0
      @current_volume = Volume.find_by_id(volume_id)
    else
      @current_volume = @volumes.try(:last)
    end
  end

  def framing
    @pictures = Picture.all.select{|pic| pic.album.name.capitalize == "Frames"}
  end

  def index
    @pictures = Picture.where("slideshow = ?", true).sort_by{|p| p.album.ordering}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact.html.haml
.container
  .content.contact
    .center
      %p If you would like to make a purchase, or if you have any questions,
      %p please e-mail or call at your convenience.
      %br
      %p
        %strong Chris Gordon
      %p
        %strong +1 (312) 527 1036
      %p
      %a{:href => "mailto:cgordonphoto@gmail.com"}
        %strong cgordonphoto@gmail.com

app/views/home/about.html.haml
.container
  %script{:src => 'galleria.classic.js'}
  .row
    %h3.light-grey.center{style: "margin-top:10px;margin-bottom:25px;"}
      About the Artist
    .span7.light-grey.about-text
      %p Chris Gordon began photography as a teen. She spent many hours in the darkroom throughout High School and College. With the advent of the digital camera, she immersed herself in it once again.
      %p Since then she has travelled to parts of Africa, South America, Asia, Europe and the Middle East.
      %p “I am so grateful to have had the opportunity to see these diverse parts of the world. Meeting interesting people and establishing relationships is a valuable experience.”
      %p She particularly enjoys the challenge of wildlife photography; anything (or nothing!) can happen on any given day. There are no guarantees – which make a sighting, and a captured photograph, all the more special.
      %p Proceeds from the sale of her photographs go toward those in need in the areas she has visited, including: women farmers in Kenya, Bwindi Community Hospital in Southwestern Uganda, refugee girls and orphaned schoolchildren in Nairobi and those fighting to save elephants from poachers in East Africa.
    .span5
      .row.center{:style=>"margin-left:auto;margin-right:auto;margin-top:0px;"}
        -#TODO: use cloudinary? cl_image_tag
        =image_tag "self-portrait.jpg", :height => "309", :width => "216", :class=>'img-polaroid'
      .row.center.light-grey{:style=>"font-size:13px;margin-left:auto;margin-right:auto;"}
        %p Member: North American Nature Photography Association
        %p Photographic Society of America
        %p Center for Photographic Art, Carmel, CA
  .row
    %hr
    .span12.contact-info.light-grey.center
      %p If you have a question or would like to make a purchase, please e-mail or call at your convenience.
      %p +1 (312) 527-1036
      %a{:href => "mailto:cgordonphoto@gmail.com"}
        %p cgordonphoto@gmail.com
%br
%br

app/views/home/blog.html.haml
- # TODO: paginate
.container-fluid
  .row-fluid.min-buffer
    .span2
      = render 'home/blog/sidebar'
    .span10
      -# TODO: kill?
      %script{:src => 'galleria.classic.js'}
      .row
        .center
          .light-grey
            %br
              - if @current_volume
                %br
                - @current_volume.posts.sort_by(&:created_at).reverse.each do |post|
                  .row
                    - if post.picture.present?
                      .span7
                        .row
                          %h3= post.title
                          %h4= post.created_at.strftime("%B %d, %Y")
                        .row
                          %br
                          %h4{:style => "line-height:26px"}= post.body
                      .span5
                        .row
                          = link_to cl_image_tag(post.picture.cloudinary_public_id, :width => 300, quality: 'jpegmini', sign_url: true, dpr: :auto, :title=>"#{post.picture.title}", :style => "padding:25px;"), picture_path(post.picture)
                    - else
                      .span12
                        .row
                          %h3= post.title
                        .row
                          %h4= post.created_at.strftime("%B %d, %Y")
                          %br
                          %h4{:style => "line-height:26px"}= post.body
                  .row
                    %br
                    %hr

              - else # TODO: remove after first blog post
                .row
                  %h1= "Coming soon!"
                  %br
                  %br

app/views/home/contact.html.haml
= render "contact"

app/views/home/framing.html.haml
.row-fluid
  %script{:src => 'galleria.classic.js'}
  .span1
    %br
    %br
    = link_to 'Back', pricing_path, :style => 'color:lightgrey;margin-left:15%;font-size:13px;'

  .span11
    - @pictures.in_groups_of(4).each do |picture_group|
      .row{:style=>"text-align:center;"}
        - picture_group.compact.each do |picture|
          .span3
            .row
              = link_to cl_image_tag(picture.cloudinary_public_id, :width => 200, quality: 'jpegmini', sign_url: true, dpr: :auto, :title=>"#{picture.title}", :style => "padding:25px;"), picture_path(picture)
            .row
              .center.frame-titles
                = picture.title

app/views/home/index.html.haml
.container-fluid.home
  #galleria{style: "margin-left:auto; margin-right:auto; max-width:100%;"}
    - @pictures.each do |picture|
      = cl_image_tag(picture.cloudinary_public_id, quality: 'jpegmini', sign_url: true, dpr: :auto, style: "max-width:100%")
  %script{:src => 'galleria.classic.js'}
  :javascript
    Galleria.configure({
                        debug: false,
                        autoplay: 2000,
                        fullscreenDoubleTap: true,
                        showCounter: false,
                        showImagenav: false,
                        showInfo: false,
                        thumbDisplayOrder: false,
                        thumbnails: false,
                        transition: 'fade',
                        touchTransition: 'fadeslide',
                        transitionSpeed: 3000,
                        trueFullscreen: true,
                        pauseOnInteraction: false
                       });
    Galleria.ready(function() {
      this.bind("pause", function(e) {
        var gallery = Galleria.get(0); // gallery is now the first galleria instance
        gallery.play();
      });
    });

    Galleria.run('#galleria');

app/views/home/pricing.html.haml
.container
  %script{:src => 'galleria.classic.js'}
  .row
    .center.pricing-table
      .span6
        %br
        %table.table.table-striped.table-bordered
          %tr
            %th{:colspan => 2}
              %h3.light-blue-shadow{:style => 'text-align:center;'} Photo Prints
          %tr.price-style
            %td 8 x 10
            %td $60
          %tr.price-style
            %td 11 x 14
            %td $75
          %tr.price-style
            %td 12 x 18
            %td $90
        %br
        %table.table.table-striped.table-bordered
          %tr
            %th{:colspan => 2}
              %h3.light-blue-shadow{:style => 'text-align:center;'} Canvas Wrap
          %tr.price-style
            %td 12 x 18
            %td $85
          %tr.price-style
            %td 16 x 20
            %td $95
          %tr.price-style
            %td 18 x 24
            %td $115
          %tr.price-style
            %td 20 x 30
            %td $140
        %p.light-grey Other sizes are available
      .span6
        .light-grey
          %br
          %h3
            Please
            = link_to "click here", framing_path
            to see framing options
          %p Framing is custom and varies depending on the material, matting, etc.
          %p Please call to discuss your specific needs
          %br
          %hr
          %br
          %p Images are displayed in lower resolution for ease of viewing on your computer. Actual prints will be of the highest quality.
          %p Please note that color calibration varies from monitor to monitor. Final product may appear slightly different than what you see on your computer.
          %br
          %hr
          %br
        .contact-info.light-grey
          %p If you have a question or would like to make a purchase, please e-mail or call at your convenience.
          %p +1 (312) 527-1036
          %a{:href => "mailto:cgordonphoto@gmail.com"}
            %p cgordonphoto@gmail.com