config/routes.rb
Photo::Application.routes.draw do
  get "home/index"

  resources :user_sessions, :only => [:new, :create, :destroy]
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :admin, :only => [:index]
  resources :albums
  resources :gallery, :only => [:index]
  match "/gallery_reset" => "gallery#reset"
  resources :pictures, :except => [:index]
  resources :posts, :only => [:new, :create, :index, :destroy]
  resources :volumes, :only => [:new, :create, :index, :destroy] # is this needed?

  match "/about" => "home#about"
  match "/blog" => "home#blog"
  match "/framing" => "home#framing"
  match "/pricing" => "home#pricing"

  match "/set_gallery_session" => "application#set_gallery_session", via: :post
  match "/get_gallery_session" => "application#get_gallery_session", via: :get

  root :to => 'home#index'

end

app/models/picture.rb
require 'RMagick' #TODO REMOVE?

class Picture < ActiveRecord::Base
  include Magick

  #TODO - migration - remove thumbnail
  belongs_to :album

  attr_accessible :description, :title, :filename, :content_type, :slideshow, :album_id, :ordering, :cloudinary_url, :cloudinary_public_id

  validates_presence_of :title, :filename #, :album_id # TODO: allow nil for blog post:
  validates_uniqueness_of :filename, :cloudinary_url, :allow_blank => true # TODO: ensure nil can be saved initially, for blog post

  #TODO: move this to album?
  def self.generate_ordering(album)
    return 0 if album.ordering_list.empty?
    ordering = album.ordering_list.sort
    ordering.last + 1
  end

  def thumbnail_name
    filename.gsub(/.jpg/, "_thumb.jpg")
  end

  def update_picture(new_attributes)
    album = Album.find_by_name(new_attributes.delete('album'))
    update_attributes(new_attributes.merge!({album_id: album.id}))
  end

  protected

  def self.create(params)
    return false unless valid_params?(params)

    picture = Picture.new

    picture.title = params[:title]
    picture.description = params[:description]
    #picture.location = params[:location]
    picture.content_type = params[:photo_file].content_type
    picture.filename = SecureRandom.random_number(999).to_s + "-" + params[:photo_file].original_filename
    picture.slideshow = params[:slideshow] == "1"

    album = Album.find_by_name(params[:album])
    picture.album_id = album.id

    picture.ordering = generate_ordering album
    # p picture.inspect
    # p picture.valid?
    # p picture.errors
    p "$$$$$$$"

    #not needed after Cloudinary is used
    #upload(params[:photo_file])

    return false unless picture.save

    response = Cloudinary::Uploader.upload(params[:photo_file])

    #no thumbnail creation for now
    #create_thumbnail(params[:photo_file])

    picture.cloudinary_url = response["url"]
    picture.cloudinary_public_id = "#{response["public_id"]}.#{response["format"]}"
    picture.save
  end

  def self.remove_from_cloudinary(cloudinary_public_id)
    public_id = cloudinary_public_id.split("\.").first
    Cloudinary::Uploader.destroy(public_id)
  end

  private

  def self.valid_params?(params)
    return false if params[:title].nil? || params[:description].nil? || params[:photo_file].nil?
    true
  end

  def self.upload(image)
    File.open(Rails.root.join('public', 'assets', image.original_filename), 'wb') do |file|
      file.write(image.read)
    end
  end

  def self.create_thumbnail(uploaded_image)
    filename = uploaded_image.original_filename
    image = Image.read(Rails.root.join('app', 'assets', 'images', uploaded_image.original_filename)).first
    thumbnail = image.thumbnail(0.099)
    thumb_name = filename.gsub(/.jpg/, "_thumb.jpg")

    File.open(Rails.root.join('app', 'assets', 'images', thumb_name), 'wb') do |file|
      file.write(thumbnail)
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  skip_before_filter :require_login, except: [:new, :create, :edit, :update, :destroy]
  skip_before_filter :clear_gallery_session
  before_filter :get_picture, except: [:new, :create]

  def show
    @album = @picture.album
  end

  def new
    @picture = Picture.new
  end

  def create
    picture_params = params[:picture]

    if Picture.create(picture_params)
      flash[:notice] = 'You have added this picture!'
      redirect_to(Picture.last)
    else
      flash[:error] = 'There was an error adding this picture!'
      redirect_to gallery_index_url #TODO: redirect to pictures new page?
    end
  end

  def update
    new_attributes = params[:picture]

    if @picture.update_picture(new_attributes)
      flash[:notice] = 'You have successfully updated this picture!'
      redirect_to(@picture)
    else
      flash[:error] = 'There was an error saving your changes!'
      render :edit
    end
  end

  def destroy
    cloudinary_public_id = @picture.cloudinary_public_id

    if @picture.destroy
      flash[:notice] = 'You have successfully deleted this picture!'

      response = Picture.remove_from_cloudinary(cloudinary_public_id)
      flash[:error] = 'The picture was deleted but there was a problem removing it from Cloudinary!' if response == {"result"=>"not found"}

      redirect_to admin_index_url
    else
      flash[:error] = 'There was a problem with deleting this picture!'
      redirect_to edit_picture_path(@picture)
    end
  end

  private

  def get_picture
    @picture = Picture.find(params[:id])
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def back_to_gallery_or_album_copy
    if @album.name.downcase == 'frames'
      "Back to Frames"
    elsif @album.name.downcase == 'blog'
      "Back to Blog"
    elsif cookies[:gallery].present?
      "Back to #{@album.name}"
    else
      "Back to Gallery"
    end
  end

  def previous_page_path
    case @album.name.downcase
    when "frames"
      framing_path
    when "blog"
      blog_path
    else
      gallery_index_path
    end
  end
end

app/views/pictures/edit.html.haml
%h1.center Edit this photo
%script{:src => 'galleria.classic.js'}

.row-fluid
  .span2
    %br
    %br
    = link_to 'Back', :back, :style => 'color:lightgrey;margin-left:15%;font-size:13px;'

  .span8
    .center
      = cl_image_tag @picture.cloudinary_public_id, {:style=>"max-width:800px;max-height:700px;"}

      .light-grey
        %br
        %h4
          Current title:
        = @picture.title
        %h4
          Current description:
        = @picture.description

        %h4 Part of slideshow?
        = @picture.slideshow

%hr
.row.center.light
  %h3 Make your changes below
  %br

  = form_for @picture, :url => picture_path do |f|
    = label_tag :title, "Title (required)"
    = f.text_area :title, :rows => 2

    = label_tag :description, "Description"
    = f.text_area :description, :rows => 5

    =# label_tag :location, "Location"
    =# f.text_area :location
    =# label_tag :album_label, "Select an album"
    %br
    %br
    = f.select :album, options_for_select(Album.all.map(&:name).map(&:titleize).sort, :selected => @picture.album.name.titleize)
    %br

    %br
    = label_tag :slideshow_label, "Part of slideshow?"
    = f.check_box :slideshow, :checked => @picture.slideshow
    = label_tag :checkbox_label, "Yes"

    %br
    %br
    %br

    = f.submit 'Submit changes', class: "btn btn-primary radius"

%hr
.row.center
  = link_to("Delete this picture", picture_path(@picture), method: :delete, class: "btn btn-danger radius", confirm: "Are you sure you want to permanently delete this picture?")

app/views/pictures/new.html.haml
%h1.center Add a new photo

.center.light
  %script{:src => 'galleria.classic.js'}
  = form_for @picture, :url => pictures_path do |f|
    .bold{:style=>"color:lightgrey;"}
      = label_tag :upload_photo, "Choose photo to upload (required):"
    %br
    = f.file_field :photo_file
    %br
    %br

    =# label_tag :upload_thumbnail, "Upload the matching thumbnail"
    =# f.file_field :thumbnail_file

    = label_tag :title, "Title (required)"
    = f.text_area :title, :rows => 2

    = label_tag :description, "Description"
    = f.text_area :description, :rows => 5

    =# label_tag :location, "Location"
    =# f.text_area :location
    =# label_tag :album_label, "Select an album"
    %br
    %br
    = f.select :album, options_for_select(Album.all.map(&:name).map(&:titleize).sort), :prompt => 'Please select an album (required)'
    %br

    %br
    = label_tag :slideshow_label, "Part of slideshow?"
    = f.check_box :slideshow
    = label_tag :checkbox_label, "Yes"

    %br
    %br
    %br

    = f.submit 'Add picture', class: "btn btn-primary"

app/views/pictures/show.html.haml
.row-fluid
  %script{src: 'galleria.classic.js'}
  .row
    .span1
    .span6{style: "margin: 0px; min-width: 200px"}
      .center
        = p @picture.cloudinary_public_id
        = cl_image_tag(@picture.cloudinary_public_id, quality: 'jpegmini', sign_url: true, dpr: :auto, style: "max-width:100%;max-height:700px;min-width:200px")

        -#TODO -style description, color
        .light-grey
          %br
          %h3= @picture.title
          %h5= @picture.description unless @album.name.downcase == "blog"

    .span5.light-grey#album-info{style: "margin-top: 0px; margin-bottom: 0px; text-align: center; min-width: 150px;"}
      %br
      %br
      - unless @album.name.downcase == "blog"
        %h4= "Album:"
        %h3= @picture.album.name
        %h5= "#{index_within_album(@picture)} of #{@album.pictures.size}"
        - unless first_picture?
          = link_to 'Previous', picture_path(previous_picture), :style => 'color:lightgrey;font-size:16px;text-decoration:underline;'
        - if display_hashmark?
          %span= "|"
        - unless last_picture?
          = link_to 'Next', picture_path(next_picture), :style => 'color:lightgrey;font-size:16px;text-decoration:underline;'

      #back-to-gallery{style: "margin-left:auto;margin-right:auto; min-width:225px; max-width:100%; text-align:center;"}
        %br
        %br
        = link_to back_to_gallery_or_album_copy, previous_page_path, :style => 'color:lightgrey;margin-left:0px;font-size:16px;text-decoration:underline;'